/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singin.interfaceProfesseur;

import singin.DataNotFound;
import singin.Projet;

/**
 *
 * @author matt
 */
public class GUIprofesseur extends javax.swing.JFrame {

  public enum ETAT {

	NOUVEAUPROJET, SELECTIONPROJET, DETAILPROJET
  };

  private ETAT etat;

  private Projet projet;

  /**
   * Creates new form GUIprof
   */
  public GUIprofesseur() {
	initComponents();
	selectionProjetPanel.setjFrame(this);
	nouveauProjetPanel.setjFrame(this);
	detailProjetPanel.setjFrame(this);

	etat = ETAT.SELECTIONPROJET;
	ouvertureSelection();
	this.setSize(720, 600);

	projet = null;

  }

  public void ouvrirProjet(Projet p) {
	switch (etat) {
	  case SELECTIONPROJET:
		etat = ETAT.DETAILPROJET;
		projet = p;
		detailProjetPanel.ouvrirProjet(p);
		ouvertureDetail();
		break;
	  case DETAILPROJET:
		throw new RuntimeException();
	  case NOUVEAUPROJET:
		throw new RuntimeException();
	}
  }

  public void fermerProjet() {
	switch (etat) {
	  case DETAILPROJET:
		etat = ETAT.SELECTIONPROJET;
		projet = null;
		ouvertureSelection();
		break;
	  case SELECTIONPROJET:
		throw new RuntimeException();
	  case NOUVEAUPROJET:
		etat = ETAT.SELECTIONPROJET;
		projet = null;
		ouvertureSelection();
		selectionProjetPanel.actualiserListeProjet();
		break;
	}
  }

  public void nouveauProjet() {
	switch (etat) {
	  case DETAILPROJET:
		throw new RuntimeException();
	  case SELECTIONPROJET:
		etat = ETAT.NOUVEAUPROJET;
		ouvertureNouveau();
		nouveauProjetPanel.ouverture();
		break;
	  case NOUVEAUPROJET:
		throw new RuntimeException();
	}
  }
  
  public void fermer(){
	this.dispose();
  }

  private void ouvertureDetail() {
	detailProjetPanel.setVisible(true);
	selectionProjetPanel.setVisible(false);
	nouveauProjetPanel.setVisible(false);
  }

  private void ouvertureNouveau() {
	detailProjetPanel.setVisible(false);
	selectionProjetPanel.setVisible(false);
	nouveauProjetPanel.setVisible(true);
  }

  private void ouvertureSelection() {
	detailProjetPanel.setVisible(false);
	selectionProjetPanel.setVisible(true);
	nouveauProjetPanel.setVisible(false);
  }

  public Projet getProjet() {
	return projet;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    selectionProjetPanel = new singin.interfaceProfesseur.SelectionProjetPanel();
    detailProjetPanel = new singin.interfaceProfesseur.DetailProjetPanel();
    nouveauProjetPanel = new singin.interfaceProfesseur.NouveauProjetPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(detailProjetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(nouveauProjetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(selectionProjetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 12, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(selectionProjetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(detailProjetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(nouveauProjetPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(0, 22, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
	 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		  javax.swing.UIManager.setLookAndFeel(info.getClassName());
		  break;
		}
	  }
	} catch (ClassNotFoundException ex) {
	  java.util.logging.Logger.getLogger(GUIprofesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	  java.util.logging.Logger.getLogger(GUIprofesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	  java.util.logging.Logger.getLogger(GUIprofesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	  java.util.logging.Logger.getLogger(GUIprofesseur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	  public void run() {
		new GUIprofesseur().setVisible(true);
	  }
	});
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private singin.interfaceProfesseur.DetailProjetPanel detailProjetPanel;
  private singin.interfaceProfesseur.NouveauProjetPanel nouveauProjetPanel;
  private singin.interfaceProfesseur.SelectionProjetPanel selectionProjetPanel;
  // End of variables declaration//GEN-END:variables
}
