/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singin.interfaceProfesseur;

import singin.*;
import singin.Eleve;
import singin.UserJList;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ListModel;
import net.beadsproject.beads.data.Sample;

/**
 *
 * @author Mox
 */
public class NouveauProjetPanel extends javax.swing.JPanel {

    /**
     * Creates new form NouveauProjet
     */
    private ArrayList<Eleve> lesParticipants;
    private Lecteur lecteur;
    private String fileName;
    private Professeur leProf;
    private UserJList userSelectionne;

    private GUIprofesseur jFrame;

    public NouveauProjetPanel() {
        initComponents();
        chargerListeEleves();
        lesParticipants = new ArrayList<>();
        lecteur = new Lecteur();
        //pour la démonstration, on récupere un prof au hasard
        leProf = ConsoleBdd.getBdd().getProfesseurs().get(1); 
        System.out.println(leProf.toString());
        fileName = "p" + (ConsoleBdd.getBdd().getProjets().size() + 2) + "sample" + 1 + ".wav";
    }
	
	public void ouverture(){
	  nomProjetTextBox.setText(null);
	  consignesTextBox.setText(null);
	  lesParticipants = new ArrayList<>();
	  chargerListeParticipants();
	}

    public void chargerListeEleves() {
        ListModel<UserJList> modele;
        modele = ConsoleBdd.getBdd().getUsersJList();
        elevesList.setModel(modele);
    }

    public void ajouterParticipant(Eleve unEleve) {
        lesParticipants.add(unEleve);
        chargerListeParticipants();
    }

    public void supprimerParticipant(Eleve unEleve) {
        lesParticipants.remove(unEleve);
    }

    public void chargerListeParticipants() {
        DefaultListModel<UserJList> res = new DefaultListModel<>();
        if (lesParticipants.size() != 0) {
            for (Eleve e : lesParticipants) {
                res.addElement(e.getUserJList());
                //System.out.println("test");
            }
            ListModel<UserJList> modele;
            modele = res;
            participantsList.setModel(modele);
            participantsList.repaint();
        } else {
            System.out.println("Vide");
			participantsList.setModel(res);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    titreLabel = new javax.swing.JLabel();
    nomProjetLabel = new javax.swing.JLabel();
    consignesLabel = new javax.swing.JLabel();
    participantsLabel = new javax.swing.JLabel();
    baseTravailLabel = new javax.swing.JLabel();
    nomProjetTextBox = new javax.swing.JTextField();
    scroll_consigne = new javax.swing.JScrollPane();
    consignesTextBox = new javax.swing.JTextArea();
    scroll_eleve = new javax.swing.JScrollPane();
    elevesList = new javax.swing.JList();
    scroll_participant = new javax.swing.JScrollPane();
    participantsList = new javax.swing.JList();
    ajouterButton = new javax.swing.JButton();
    retirerButton = new javax.swing.JButton();
    recButton = new javax.swing.JButton();
    playButton = new javax.swing.JButton();
    stopButton = new javax.swing.JButton();
    validerButton = new javax.swing.JButton();
    annulerButton = new javax.swing.JButton();

    titreLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    titreLabel.setText("NOUVEAU PROJET");

    nomProjetLabel.setText("Nom du projet :");

    consignesLabel.setText("Consignes :");

    participantsLabel.setText("Choix des participants :");

    baseTravailLabel.setText("Base de travail");

    consignesTextBox.setColumns(20);
    consignesTextBox.setRows(5);
    scroll_consigne.setViewportView(consignesTextBox);

    elevesList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    elevesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        elevesListValueChanged(evt);
      }
    });
    scroll_eleve.setViewportView(elevesList);

    scroll_participant.setViewportView(participantsList);

    ajouterButton.setText(">");
    ajouterButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ajouterButtonActionPerformed(evt);
      }
    });

    retirerButton.setText("<");

    recButton.setText("Rec");
    recButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        recButtonActionPerformed(evt);
      }
    });

    playButton.setText("Play");
    playButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        playButtonActionPerformed(evt);
      }
    });

    stopButton.setText("Stop");
    stopButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stopButtonActionPerformed(evt);
      }
    });

    validerButton.setText("Valider et partager");
    validerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        validerButtonActionPerformed(evt);
      }
    });

    annulerButton.setText("Annuler");
    annulerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        annulerButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(25, 25, 25)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(participantsLabel)
          .addGroup(layout.createSequentialGroup()
            .addGap(210, 210, 210)
            .addComponent(titreLabel))
          .addGroup(layout.createSequentialGroup()
            .addComponent(nomProjetLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(nomProjetTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(baseTravailLabel)
            .addGap(14, 14, 14)
            .addComponent(recButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(playButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(stopButton))
          .addGroup(layout.createSequentialGroup()
            .addComponent(consignesLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(scroll_consigne, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(annulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(scroll_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(retirerButton)
              .addComponent(ajouterButton))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(scroll_participant, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(validerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)))))
        .addContainerGap(25, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(22, 22, 22)
        .addComponent(titreLabel)
        .addGap(24, 24, 24)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nomProjetLabel)
          .addComponent(nomProjetTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(13, 13, 13)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(baseTravailLabel)
          .addComponent(recButton)
          .addComponent(playButton)
          .addComponent(stopButton))
        .addGap(12, 12, 12)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(consignesLabel)
          .addComponent(scroll_consigne, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(participantsLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(scroll_eleve, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(scroll_participant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(ajouterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(retirerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addGap(30, 30, 30)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(validerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(annulerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void validerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerButtonActionPerformed
	  try {
		String nomProjet = nomProjetTextBox.getText();
		String consignes = consignesTextBox.getText();
		ListModel<Eleve> eleves = participantsList.getModel();
		
		//Creation des objet
		Bdd bdd = ConsoleBdd.getBdd();
		Projet p = new Projet(nomProjet);
		int numProj = bdd.newProjet(p);
		Enregistrement enr = new Enregistrement(fileName, leProf);
		
		// Ajout des objets dans bdd.
		bdd.addProfesseurToProject(numProj, leProf);
		bdd.addEnregistrementToProjet(numProj, enr);
		bdd.addConsigneToProjet(numProj, consignes);
		for(Eleve e: lesParticipants){
		  bdd.addEleveToProject(numProj, e);
		}
		
		
		System.out.println(bdd.getProjet(numProj).toString());
	  } catch (DataNotFound ex) {
		Logger.getLogger(NouveauProjetPanel.class.getName()).log(Level.SEVERE, null, ex);
	  }
	  
	  jFrame.fermerProjet();
  }//GEN-LAST:event_validerButtonActionPerformed

    private void ajouterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterButtonActionPerformed
        if(userSelectionne != null){
            lesParticipants.add((Eleve) userSelectionne.getUser());
        }
        chargerListeParticipants();
    }//GEN-LAST:event_ajouterButtonActionPerformed

    private void recButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recButtonActionPerformed
        lecteur.removeSamples();
        lecteur.rec(fileName);

    }//GEN-LAST:event_recButtonActionPerformed

    private void playButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playButtonActionPerformed
        try {
            lecteur.addSample(new Sample(fileName));
        } catch (IOException ex) {
            Logger.getLogger(NouveauProjetPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        lecteur.play();
    }//GEN-LAST:event_playButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        lecteur.stop();
    }//GEN-LAST:event_stopButtonActionPerformed

    private void elevesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_elevesListValueChanged
        userSelectionne = (UserJList) elevesList.getSelectedValue();
    }//GEN-LAST:event_elevesListValueChanged

    private void annulerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerButtonActionPerformed
	  jFrame.fermerProjet();
    }//GEN-LAST:event_annulerButtonActionPerformed
       
    public void setjFrame(GUIprofesseur jFrame) {
        this.jFrame = jFrame;
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton ajouterButton;
  private javax.swing.JButton annulerButton;
  private javax.swing.JLabel baseTravailLabel;
  private javax.swing.JLabel consignesLabel;
  private javax.swing.JTextArea consignesTextBox;
  private javax.swing.JList elevesList;
  private javax.swing.JLabel nomProjetLabel;
  private javax.swing.JTextField nomProjetTextBox;
  private javax.swing.JLabel participantsLabel;
  private javax.swing.JList participantsList;
  private javax.swing.JButton playButton;
  private javax.swing.JButton recButton;
  private javax.swing.JButton retirerButton;
  private javax.swing.JScrollPane scroll_consigne;
  private javax.swing.JScrollPane scroll_eleve;
  private javax.swing.JScrollPane scroll_participant;
  private javax.swing.JButton stopButton;
  private javax.swing.JLabel titreLabel;
  private javax.swing.JButton validerButton;
  // End of variables declaration//GEN-END:variables
}
