/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singin.interfaceProfesseur;

import singin.Bdd;
import singin.ConsoleBdd;
import singin.Projet;
import singin.ProjetJComboBox;
import javax.swing.ComboBoxModel;

/**
 *
 * @author Mox
 */
public class SelectionProjetPanel extends javax.swing.JPanel {
  
  private GUIprofesseur jFrame;
  private Bdd bdd;

    /**
     * Creates new form listProj_panel
     */
    public SelectionProjetPanel() {
        initComponents();
		
		chargerListeProjets();
    }
	
	public void chargerListeProjets(){
	  
	  ComboBoxModel<ProjetJComboBox> model;
	  model = ConsoleBdd.getBdd().getProjetsJComboBox();
	  projetComboBox.setModel(model);
	}

  public void setjFrame(GUIprofesseur jFrame) {
	this.jFrame = jFrame;
  }
	
	
    
 // <editor-fold defaultstate="collapsed" desc="Methodes"> 
    public void actualiserListeProjet(){
        projetComboBox.removeAllItems();
		chargerListeProjets();
    }
    
// </editor-fold> 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    projetComboBox = new javax.swing.JComboBox();
    ouvrirButton = new javax.swing.JButton();
    rafraichirButton = new javax.swing.JButton();
    titreLabel = new javax.swing.JLabel();
    nouveauProjetButton = new javax.swing.JButton();
    fermerButton = new javax.swing.JButton();

    projetComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    ouvrirButton.setText("Ouvrir");
    ouvrirButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        ouvrirButtonActionPerformed(evt);
      }
    });

    rafraichirButton.setText("rafraichir la liste");

    titreLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    titreLabel.setText("Liste des projets");

    nouveauProjetButton.setText("Créer un nouveau projet");
    nouveauProjetButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        nouveauProjetButtonActionPerformed(evt);
      }
    });

    fermerButton.setText("Fermer");
    fermerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fermerButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(178, 178, 178)
            .addComponent(titreLabel)
            .addGap(0, 182, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(projetComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(nouveauProjetButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addGroup(layout.createSequentialGroup()
                .addComponent(ouvrirButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rafraichirButton))))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(fermerButton)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(titreLabel)
        .addGap(36, 36, 36)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(projetComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ouvrirButton)
          .addComponent(rafraichirButton))
        .addGap(47, 47, 47)
        .addComponent(nouveauProjetButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
        .addComponent(fermerButton)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void nouveauProjetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nouveauProjetButtonActionPerformed
    jFrame.nouveauProjet();
  }//GEN-LAST:event_nouveauProjetButtonActionPerformed

  private void ouvrirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ouvrirButtonActionPerformed
    Projet projet;
	projet = ((ProjetJComboBox)projetComboBox.getSelectedItem()).getProjet();
	jFrame.ouvrirProjet(projet);
  }//GEN-LAST:event_ouvrirButtonActionPerformed

  private void fermerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerButtonActionPerformed
    jFrame.fermer();
  }//GEN-LAST:event_fermerButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton fermerButton;
  private javax.swing.JButton nouveauProjetButton;
  private javax.swing.JButton ouvrirButton;
  private javax.swing.JComboBox projetComboBox;
  private javax.swing.JButton rafraichirButton;
  private javax.swing.JLabel titreLabel;
  // End of variables declaration//GEN-END:variables
}
