/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singin.interfaceEleve;

/**
 *
 * @author matt
 */
public class DetailRecPanel extends javax.swing.JPanel {

  /**
   * Creates new form DetailRecPanel
   */
  public DetailRecPanel() {
	initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    nomLabel = new javax.swing.JLabel();
    prenomLabel = new javax.swing.JLabel();
    instrumentButton = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    playButton = new javax.swing.JButton();
    pauseButton = new javax.swing.JButton();
    stopButton = new javax.swing.JButton();

    jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 51));
    jLabel1.setText("Detail de l'enregistrement ...");

    nomLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    nomLabel.setText("Nom :");

    prenomLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    prenomLabel.setText("Prenom :");

    instrumentButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    instrumentButton.setText("Instrument :");

    playButton.setText("Play");

    pauseButton.setText("Pause");

    stopButton.setText("Stop");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(instrumentButton)
              .addComponent(prenomLabel)
              .addComponent(nomLabel)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(93, 93, 93)
            .addComponent(playButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(pauseButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(stopButton)))
        .addContainerGap(71, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(nomLabel)
        .addGap(18, 18, 18)
        .addComponent(prenomLabel)
        .addGap(18, 18, 18)
        .addComponent(instrumentButton)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(playButton)
          .addComponent(pauseButton)
          .addComponent(stopButton))
        .addGap(56, 56, 56))
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel instrumentButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JLabel nomLabel;
  private javax.swing.JButton pauseButton;
  private javax.swing.JButton playButton;
  private javax.swing.JLabel prenomLabel;
  private javax.swing.JButton stopButton;
  // End of variables declaration//GEN-END:variables
}
