/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singin.interfaceEleve;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListModel;
import singin.ConsoleBdd;
import singin.DataNotFound;
import singin.Enregistrement;
import singin.EnregistrementJList;
import singin.Lecteur;
import singin.Projet;

/**
 *
 * @author Othmane
 */
public class DetailProjetPanel extends javax.swing.JPanel {

  private GUIeleve jFrame;
  private Enregistrement eSelect;
  private Lecteur lecteur;
  private Enregistrement monEnregistrement;

  private enum ETAT {

	PLAYALL, STOPSANS, STOPAVEC, PLAYONE, PLAYMON, ARME, REC;
  };

  private ETAT etat;

  public DetailProjetPanel() {
	initComponents();
	etat = ETAT.STOPSANS;
	activateStopSans();
	detailButton.setEnabled(false);

  }

  public void setjFrame(GUIeleve jFrame) {
	this.jFrame = jFrame;
  }

  
  
  public void activateStopAvec() {
	playAllButton.setEnabled(true);
	stopAllButton.setEnabled(false);
	playOneButton.setEnabled(true);
	stopOneButton.setEnabled(false);
	playMonButton.setEnabled(true);
	stopMonButton.setEnabled(false);
	recButton.setEnabled(true);
	recButton.setSelected(false);

  }
  
  public void activateStopSans() {
	playAllButton.setEnabled(true);
	stopAllButton.setEnabled(false);
	playOneButton.setEnabled(true);
	stopOneButton.setEnabled(false);
	playMonButton.setEnabled(false);
	stopMonButton.setEnabled(false);
	recButton.setEnabled(true);
	recButton.setSelected(false);

  }

  public void activatePlayAll() {
	playAllButton.setEnabled(false);
	stopAllButton.setEnabled(true);
	playOneButton.setEnabled(false);
	stopOneButton.setEnabled(false);
	playMonButton.setEnabled(false);
	stopMonButton.setEnabled(false);
	recButton.setEnabled(false);
  }

  public void activatePlayOne() {
	playAllButton.setEnabled(false);
	stopAllButton.setEnabled(false);
	playOneButton.setEnabled(false);
	stopOneButton.setEnabled(true);
	playMonButton.setEnabled(false);
	stopMonButton.setEnabled(false);
	recButton.setEnabled(false);
  }

  public void activatePlayMon() {
	playAllButton.setEnabled(false);
	stopAllButton.setEnabled(false);
	playOneButton.setEnabled(false);
	stopOneButton.setEnabled(false);
	playMonButton.setEnabled(false);
	stopMonButton.setEnabled(true);
	recButton.setEnabled(false);
  }
  
  public void activateArme(){
	playAllButton.setEnabled(false);
	stopAllButton.setEnabled(false);
	playOneButton.setEnabled(false);
	stopOneButton.setEnabled(false);
	playMonButton.setEnabled(true);
	stopMonButton.setEnabled(true);
	recButton.setEnabled(true);
  }
  
  public void activateRec(){
	playAllButton.setEnabled(false);
	stopAllButton.setEnabled(false);
	playOneButton.setEnabled(false);
	stopOneButton.setEnabled(false);
	playMonButton.setEnabled(false);
	stopMonButton.setEnabled(true);
	recButton.setEnabled(false);
  }

  public void demarrerLectureAll() {
	//Demarrer le lecteur
  }

  public void arreterLectureAll() {
	// arreter le lecteur
  }
  
  private void chargerListeEnregistrements() throws DataNotFound{
	Projet projet = jFrame.getProjet();
	ListModel<EnregistrementJList> model;
	
	model = ConsoleBdd.getBdd().getEnregistrementsJList(projet.getIdProjet());
	enregistrementsList.setModel(model);
  }

  public void ouvrirProjet() throws DataNotFound {
	
	etat = ETAT.STOPSANS;
	activateStopSans();
	detailButton.setEnabled(false);
	monEnregistrement = null;
	lecteur = null;
	eSelect = null;
	
	chargerListeEnregistrements();
	
	nomLabel.setText("");
	prenomLabel.setText("");
	instrumentLabel.setText("");
	dateLabel.setText("");
	commentaireTextArea.setText("");
	repondreTextArea.setText("");
	monRecPanel.setVisible(false);
	detailRecPanel.setVisible(false);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.ben
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    jSeparator3 = new javax.swing.JSeparator();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTextArea2 = new javax.swing.JTextArea();
    jLabel10 = new javax.swing.JLabel();
    jButton10 = new javax.swing.JButton();
    jButton11 = new javax.swing.JButton();
    jButton12 = new javax.swing.JButton();
    jButton13 = new javax.swing.JButton();
    jLabel11 = new javax.swing.JLabel();
    jLabel12 = new javax.swing.JLabel();
    jButton14 = new javax.swing.JButton();
    jScrollPane3 = new javax.swing.JScrollPane();
    jTextArea1 = new javax.swing.JTextArea();
    jLabel1 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    jScrollPane1 = new javax.swing.JScrollPane();
    enregistrementsList = new javax.swing.JList();
    enregistrementLabel = new javax.swing.JLabel();
    detailButton = new javax.swing.JButton();
    rafraichirButton = new javax.swing.JButton();
    playAllButton = new javax.swing.JButton();
    stopAllButton = new javax.swing.JButton();
    monEnregistrementButton = new javax.swing.JButton();
    fermerButton = new javax.swing.JButton();
    monRecPanel = new javax.swing.JPanel();
    commentaireLabel = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    repondreLabel = new javax.swing.JLabel();
    jSeparator2 = new javax.swing.JSeparator();
    jScrollPane4 = new javax.swing.JScrollPane();
    repondreTextArea = new javax.swing.JTextArea();
    dateLabel = new javax.swing.JLabel();
    playMonButton = new javax.swing.JButton();
    validerButton = new javax.swing.JButton();
    annulerButton = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    supprimerButton = new javax.swing.JButton();
    jScrollPane5 = new javax.swing.JScrollPane();
    commentaireTextArea = new javax.swing.JTextArea();
    stopMonButton = new javax.swing.JButton();
    recButton = new javax.swing.JToggleButton();
    detailRecPanel = new javax.swing.JPanel();
    jSeparator4 = new javax.swing.JSeparator();
    playOneButton = new javax.swing.JButton();
    pauseButton = new javax.swing.JButton();
    stopOneButton = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    nomLabel = new javax.swing.JLabel();
    prenomLabel = new javax.swing.JLabel();
    instrumentLabel = new javax.swing.JLabel();

    jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel7.setText("Commentaire du professeur :");

    jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
    jLabel8.setForeground(new java.awt.Color(0, 51, 51));
    jLabel8.setText("Mon enregistrement :");

    jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel9.setText("Répondre :");

    jTextArea2.setColumns(20);
    jTextArea2.setRows(5);
    jScrollPane2.setViewportView(jTextArea2);

    jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel10.setText("Date :");

    jButton11.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jButton11.setText("Valider");

    jButton13.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jButton13.setText("Annuler");

    jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel11.setText("Écouter");

    jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel12.setText("Ré-enregistrer");

    jButton14.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jButton14.setText("Supprimer");

    jTextArea1.setColumns(20);
    jTextArea1.setRows(5);
    jScrollPane3.setViewportView(jTextArea1);

    jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 51));
    jLabel1.setText("Projet initié par ...");

    enregistrementsList.setModel(new javax.swing.AbstractListModel() {
      String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
      public int getSize() { return strings.length; }
      public Object getElementAt(int i) { return strings[i]; }
    });
    enregistrementsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
      public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
        enregistrementsListValueChanged(evt);
      }
    });
    jScrollPane1.setViewportView(enregistrementsList);

    enregistrementLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    enregistrementLabel.setText("Liste des enregistrements :");

    detailButton.setText("Voir detail");
    detailButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        detailButtonActionPerformed(evt);
      }
    });

    rafraichirButton.setText("Raffraichir");

    playAllButton.setText("Play");
    playAllButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        playAllButtonActionPerformed(evt);
      }
    });

    stopAllButton.setText("Stop");
    stopAllButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        stopAllButtonActionPerformed(evt);
      }
    });

    monEnregistrementButton.setText("Mon enregistrement");
    monEnregistrementButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        monEnregistrementButtonActionPerformed(evt);
      }
    });

    fermerButton.setText("Fermer le projet");
    fermerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fermerButtonActionPerformed(evt);
      }
    });

    commentaireLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    commentaireLabel.setText("Commentaire du professeur :");

    jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
    jLabel2.setForeground(new java.awt.Color(0, 51, 51));
    jLabel2.setText("Mon enregistrement :");

    repondreLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    repondreLabel.setText("Répondre :");

    repondreTextArea.setColumns(20);
    repondreTextArea.setRows(5);
    jScrollPane4.setViewportView(repondreTextArea);

    dateLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    dateLabel.setText("Date :");

    validerButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    validerButton.setText("Valider");

    annulerButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    annulerButton.setText("Annuler");

    jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel3.setText("Écouter");

    jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel4.setText("Ré-enregistrer");

    supprimerButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    supprimerButton.setText("Supprimer");

    commentaireTextArea.setColumns(20);
    commentaireTextArea.setRows(5);
    jScrollPane5.setViewportView(commentaireTextArea);

    stopMonButton.setText("Stop");

    recButton.setText("jToggleButton1");

    javax.swing.GroupLayout monRecPanelLayout = new javax.swing.GroupLayout(monRecPanel);
    monRecPanel.setLayout(monRecPanelLayout);
    monRecPanelLayout.setHorizontalGroup(
      monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(monRecPanelLayout.createSequentialGroup()
        .addGroup(monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(monRecPanelLayout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
              .addComponent(jScrollPane5)
              .addComponent(jSeparator2)
              .addComponent(repondreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(supprimerButton)
              .addComponent(dateLabel)
              .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(monRecPanelLayout.createSequentialGroup()
                .addGroup(monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(playMonButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                  .addComponent(recButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(monRecPanelLayout.createSequentialGroup()
                    .addComponent(jLabel3)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stopMonButton)
                    .addGap(43, 43, 43))
                  .addGroup(monRecPanelLayout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE))))
              .addComponent(commentaireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(monRecPanelLayout.createSequentialGroup()
            .addGap(103, 103, 103)
            .addComponent(validerButton)
            .addGap(18, 18, 18)
            .addComponent(annulerButton)))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    monRecPanelLayout.setVerticalGroup(
      monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(monRecPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(dateLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stopMonButton))
          .addComponent(playMonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(recButton))
        .addGap(18, 18, 18)
        .addComponent(supprimerButton)
        .addGap(11, 11, 11)
        .addComponent(commentaireLabel)
        .addGap(12, 12, 12)
        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(repondreLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
        .addGroup(monRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(validerButton)
          .addComponent(annulerButton))
        .addContainerGap())
    );

    playOneButton.setText("Play");

    pauseButton.setText("Pause");

    stopOneButton.setText("Stop");

    jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
    jLabel5.setForeground(new java.awt.Color(0, 51, 51));
    jLabel5.setText("Detail de l'enregistrement ...");

    nomLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    nomLabel.setText("Nom :");

    prenomLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    prenomLabel.setText("Prenom :");

    instrumentLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    instrumentLabel.setText("Instrument :");

    javax.swing.GroupLayout detailRecPanelLayout = new javax.swing.GroupLayout(detailRecPanel);
    detailRecPanel.setLayout(detailRecPanelLayout);
    detailRecPanelLayout.setHorizontalGroup(
      detailRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(detailRecPanelLayout.createSequentialGroup()
        .addGroup(detailRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(detailRecPanelLayout.createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(detailRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(instrumentLabel)
              .addComponent(prenomLabel)
              .addComponent(nomLabel)
              .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(detailRecPanelLayout.createSequentialGroup()
            .addGap(93, 93, 93)
            .addComponent(playOneButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(pauseButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(stopOneButton)))
        .addContainerGap(20, Short.MAX_VALUE))
    );
    detailRecPanelLayout.setVerticalGroup(
      detailRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(detailRecPanelLayout.createSequentialGroup()
        .addGap(36, 36, 36)
        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(nomLabel)
        .addGap(18, 18, 18)
        .addComponent(prenomLabel)
        .addGap(18, 18, 18)
        .addComponent(instrumentLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
        .addGroup(detailRecPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(playOneButton)
          .addComponent(pauseButton)
          .addComponent(stopOneButton))
        .addGap(56, 56, 56))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(104, 104, 104)
            .addComponent(playAllButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(stopAllButton))
          .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(enregistrementLabel)
              .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detailButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rafraichirButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monEnregistrementButton, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addComponent(detailRecPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(261, 261, 261)
            .addComponent(fermerButton)
            .addContainerGap(246, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(monRecPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(213, 213, 213))))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(23, 23, 23)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(monRecPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(fermerButton))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(enregistrementLabel)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(detailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rafraichirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monEnregistrementButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(playAllButton)
              .addComponent(stopAllButton))
            .addGap(18, 18, 18)
            .addComponent(detailRecPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

  private void fermerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerButtonActionPerformed

	jFrame.fermerProjet();
  }//GEN-LAST:event_fermerButtonActionPerformed

    private void enregistrementsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_enregistrementsListValueChanged
	  if(!enregistrementsList.isSelectionEmpty()){
		eSelect = ((EnregistrementJList)enregistrementsList.getSelectedValue()).getEnregistrement();
		detailButton.setEnabled(true);
	  }
    }//GEN-LAST:event_enregistrementsListValueChanged

    private void playAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAllButtonActionPerformed
	  switch (etat) {
		case STOPSANS:
		  etat = ETAT.PLAYALL;
		  activatePlayAll();
		  demarrerLectureAll();
		  break;
		case PLAYALL:
		  throw new RuntimeException();
	  }
    }//GEN-LAST:event_playAllButtonActionPerformed

    private void stopAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopAllButtonActionPerformed
	  switch (etat) {
		case STOPSANS:
		  throw new RuntimeException();
		case PLAYALL:
		  etat = ETAT.STOPSANS;
		  activateStopSans();
		  arreterLectureAll();
		  break;
	  }
    }//GEN-LAST:event_stopAllButtonActionPerformed

  private void monEnregistrementButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monEnregistrementButtonActionPerformed
	
	try {
	  monEnregistrement = ConsoleBdd.getBdd().getEnregistrementProjetUser(
			  jFrame.getProjet().getIdProjet(), jFrame.getUser().getIdUser());
	  etat = ETAT.STOPAVEC;
	  activateStopAvec();
	  
	  commentaireTextArea.setText(monEnregistrement.getCommentaire());
	  
	  monRecPanel.setVisible(true);
	  
	} catch (DataNotFound ex) {
	  System.out.println("Pas d'enregistrement pour cet user");
	  monEnregistrement = null;
	  
	  
	  //Logger.getLogger(DetailProjetPanel.class.getName()).log(Level.SEVERE, null, ex);
	}
	
  }//GEN-LAST:event_monEnregistrementButtonActionPerformed

  private void detailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButtonActionPerformed
    nomLabel.setText(eSelect.getUser().getNom());
	prenomLabel.setText(eSelect.getUser().getPrenom());
	instrumentLabel.setText(eSelect.getUser().getInstrument());
	detailRecPanel.setVisible(true);
  }//GEN-LAST:event_detailButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton annulerButton;
  private javax.swing.JLabel commentaireLabel;
  private javax.swing.JTextArea commentaireTextArea;
  private javax.swing.JLabel dateLabel;
  private javax.swing.JButton detailButton;
  private javax.swing.JPanel detailRecPanel;
  private javax.swing.JLabel enregistrementLabel;
  private javax.swing.JList enregistrementsList;
  private javax.swing.JButton fermerButton;
  private javax.swing.JLabel instrumentLabel;
  private javax.swing.JButton jButton10;
  private javax.swing.JButton jButton11;
  private javax.swing.JButton jButton12;
  private javax.swing.JButton jButton13;
  private javax.swing.JButton jButton14;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel12;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JScrollPane jScrollPane4;
  private javax.swing.JScrollPane jScrollPane5;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSeparator jSeparator2;
  private javax.swing.JSeparator jSeparator3;
  private javax.swing.JSeparator jSeparator4;
  private javax.swing.JTextArea jTextArea1;
  private javax.swing.JTextArea jTextArea2;
  private javax.swing.JButton monEnregistrementButton;
  private javax.swing.JPanel monRecPanel;
  private javax.swing.JLabel nomLabel;
  private javax.swing.JButton pauseButton;
  private javax.swing.JButton playAllButton;
  private javax.swing.JButton playMonButton;
  private javax.swing.JButton playOneButton;
  private javax.swing.JLabel prenomLabel;
  private javax.swing.JButton rafraichirButton;
  private javax.swing.JToggleButton recButton;
  private javax.swing.JLabel repondreLabel;
  private javax.swing.JTextArea repondreTextArea;
  private javax.swing.JButton stopAllButton;
  private javax.swing.JButton stopMonButton;
  private javax.swing.JButton stopOneButton;
  private javax.swing.JButton supprimerButton;
  private javax.swing.JButton validerButton;
  // End of variables declaration//GEN-END:variables
}
