/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singin.interfaceEleve;

import singin.Bdd;
import singin.DataNotFound;
import singin.Eleve;


/**
 *
 * @author Othmane
 */
public class LoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    private Bdd bdd;
	
	private GUIeleve jFrame;
    
    public LoginPanel() {
        initComponents();
        bdd = new Bdd();
    }

  public void setjFrame(GUIeleve jFrame) {
	this.jFrame = jFrame;
  }

	
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    nomLabel = new javax.swing.JLabel();
    motDePasseLabel = new javax.swing.JLabel();
    nomTextField = new javax.swing.JTextField();
    motDePasseTextField = new javax.swing.JTextField();
    connexionButton = new javax.swing.JButton();
    lb_login = new javax.swing.JLabel();
    fermerButton = new javax.swing.JButton();

    jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 51));
    jLabel1.setText("Connexion");

    nomLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    nomLabel.setText("Login :");

    motDePasseLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    motDePasseLabel.setText("Mot de passe :");

    connexionButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    connexionButton.setForeground(new java.awt.Color(0, 51, 51));
    connexionButton.setText("Connexion");
    connexionButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        connexionButtonActionPerformed(evt);
      }
    });

    lb_login.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
    lb_login.setForeground(new java.awt.Color(0, 102, 102));

    fermerButton.setText("Fermer");
    fermerButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        fermerButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(lb_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
          .addComponent(jSeparator1)
          .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(motDePasseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
              .addComponent(nomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(nomTextField)
              .addComponent(motDePasseTextField)
              .addComponent(connexionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))))
        .addContainerGap(77, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(fermerButton)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(40, 40, 40)
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(nomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(nomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(motDePasseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(motDePasseTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(connexionButton)
        .addGap(18, 18, 18)
        .addComponent(lb_login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(fermerButton)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents

    private void connexionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionButtonActionPerformed
        // TODO add your handling code here:
        String nom = nomTextField.getText();
        try {
            Eleve e = bdd.getEleve(nom);
            if (e != null)
            {
                lb_login.setText("Connexion de Mr."+e.getNom());
            }else{
                lb_login.setText("Désolé, utilisateur inconnu");
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
		
		jFrame.ouvrirSelection();
    }//GEN-LAST:event_connexionButtonActionPerformed

  private void fermerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fermerButtonActionPerformed
    
	jFrame.fermer();
  }//GEN-LAST:event_fermerButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton connexionButton;
  private javax.swing.JButton fermerButton;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JLabel lb_login;
  private javax.swing.JLabel motDePasseLabel;
  private javax.swing.JTextField motDePasseTextField;
  private javax.swing.JLabel nomLabel;
  private javax.swing.JTextField nomTextField;
  // End of variables declaration//GEN-END:variables
}
