/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package singin.interfaceEleve;

/**
 *
 * @author Othmane
 */
public class MonRecPanel extends javax.swing.JPanel {

    /**
     * Creates new form MonRecPanel
     */
    public MonRecPanel() {
        initComponents();
		
		
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jSeparator1 = new javax.swing.JSeparator();
    dateLabel = new javax.swing.JLabel();
    playButton = new javax.swing.JButton();
    recButton = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    supprimerButton = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    commentaireTextArea = new javax.swing.JTextArea();
    commentaireLabel = new javax.swing.JLabel();
    repondreLabel = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    repondreTextArea = new javax.swing.JTextArea();
    validerButton = new javax.swing.JButton();
    annulerButton = new javax.swing.JButton();

    setPreferredSize(new java.awt.Dimension(400, 500));

    jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 51));
    jLabel1.setText("Mon enregistrement :");

    dateLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    dateLabel.setText("Date :");

    jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel3.setText("Écouter");

    jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    jLabel4.setText("Ré-enregistrer");

    supprimerButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    supprimerButton.setText("Supprimer");

    commentaireTextArea.setColumns(20);
    commentaireTextArea.setRows(5);
    jScrollPane1.setViewportView(commentaireTextArea);

    commentaireLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    commentaireLabel.setText("Commentaire du professeur :");

    repondreLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    repondreLabel.setText("Répondre :");

    repondreTextArea.setColumns(20);
    repondreTextArea.setRows(5);
    jScrollPane2.setViewportView(repondreTextArea);

    validerButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    validerButton.setText("Valider");

    annulerButton.setFont(new java.awt.Font("Tw Cen MT", 0, 14)); // NOI18N
    annulerButton.setText("Annuler");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
              .addComponent(jScrollPane1)
              .addComponent(jSeparator1)
              .addComponent(repondreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(supprimerButton)
              .addComponent(dateLabel)
              .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                  .addComponent(playButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(recButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3)
                  .addComponent(jLabel4)))
              .addComponent(commentaireLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(103, 103, 103)
            .addComponent(validerButton)
            .addGap(18, 18, 18)
            .addComponent(annulerButton)))
        .addContainerGap(74, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(dateLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(playButton)
          .addComponent(jLabel3))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(recButton)
          .addComponent(jLabel4))
        .addGap(18, 18, 18)
        .addComponent(supprimerButton)
        .addGap(11, 11, 11)
        .addComponent(commentaireLabel)
        .addGap(12, 12, 12)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(repondreLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(validerButton)
          .addComponent(annulerButton))
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton annulerButton;
  private javax.swing.JLabel commentaireLabel;
  private javax.swing.JTextArea commentaireTextArea;
  private javax.swing.JLabel dateLabel;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JButton playButton;
  private javax.swing.JButton recButton;
  private javax.swing.JLabel repondreLabel;
  private javax.swing.JTextArea repondreTextArea;
  private javax.swing.JButton supprimerButton;
  private javax.swing.JButton validerButton;
  // End of variables declaration//GEN-END:variables
}
